spring:
  application:
    name: user-center-backend
  profiles:
    active: dev
  session:
    timeout: 7d
    data:
      redis:
        namespace: user-center:session
        repository-type: indexed
  servlet:
    multipart:
      max-file-size: 5MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8100
  address: localhost
  compression:
    enabled: true
  servlet:
    context-path: /api
    session:
      timeout: 7d
      cookie:
        max-age: 7d

logging:
  file:
    name: logs/user-center-backend.log
  level:
    root: info
  logback:
    rollingpolicy:
      max-history: 2000
      max-file-size: 5MB
      total-size-cap: 1GB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.mlinyun.usercenterbackend.model.entity
  global-config:
    enable-sql-runner: true
    db-config:
      id-type: assign_id
      logic-delete-field: isDelete
      logic-not-delete-value: 0
      logic-delete-value: 1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: true
    username: admin
    password: admin1024
