spring:
  application:
    name: user-center-backend
    version: 1.0.0
  session:
    timeout: 7d
    data:
      redis:
        namespace: user-center:session
        repository-type: indexed
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_DATABASE_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE}
      connect-timeout: 3000
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    test-connection: true

server:
  port: ${SERVER_PORT:8100}
  address: ${SERVER_ADDRESS:localhost}
  compression:
    enabled: true
  servlet:
    context-path: /api
    session:
      timeout: 7d
      cookie:
        max-age: 7d

logging:
  file:
    name: logs/user-center-backend.log
  level:
    root: info
  logback:
    rollingpolicy:
      max-history: 2000
      max-file-size: 5MB
      total-size-cap: 1GB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.mlinyun.usercenterbackend.model.entity
  global-config:
    enable-sql-runner: true
    db-config:
      id-type: assign_id
      logic-delete-field: isDeleted
      logic-not-delete-value: 0
      logic-delete-value: 1

knife4j:
  production: true
