spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: user_center_user
    password: StrongPassword..1024
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0
      connect-timeout: 3000
  mail:
    host: smtp.163.com
    username: your-username
    password: your-password # 替换为授权码
    test-connection: true

aliyun:
  sms:
    access-key-id: your-access-key-id # 替换为你的 Access Key ID
    access-key-secret: your-access-key-secret # 替换为你的 Access Key Secret
    endpoint: dypnsapi.aliyuncs.com
    sign-name: your-sign-name # 替换为你的短信签名
    code-length: 6
    valid-time: 300
    interval: 60

cos:
  client:
    host: <your-custom-domain.com>
    secretId: <your-secret-id>
    secretKey: <your-secret-key>
    region: <your-region>
    bucket: <your-bucket-name>

logging:
  level:
    root: debug

knife4j:
  production: false
